openapi: 3.0.3
info:
  title: E-Commerce Backend API
  version: 1.2.0
  description: Temel endpointler + e-Fatura (EDM) entegrasyonu
servers:
  - url: http://localhost:3000
paths:
  /api/auth/login:
    post:
      summary: Kullanıcı girişi
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
              required: [email, password]
      responses:
        "200": { description: Başarılı giriş }
        "400": { description: Geçersiz istek }
  /api/products:
    get:
      summary: Ürün listeleme
      parameters:
        - in: query
          name: q
          schema:
            type: string
          description: Arama sorgusu
      responses:
        "200": { description: Ürün listesi }

  /api/invoices/{orderId}/send:
    post:
      summary: Siparişe bağlı e-Fatura/e-Arşiv gönderimi
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: orderId
          required: true
          schema:
            type: string
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                mode:
                  type: string
                  enum: [auto, einvoice, earchive]
                  default: auto
      responses:
        "200": { description: Gönderim yapıldı }
        "400": { description: Geçersiz istek }
        "401": { description: Yetkisiz }
  /api/invoices/{orderId}/status:
    get:
      summary: Fatura durumu
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: orderId
          required: true
          schema:
            type: string
      responses:
        "200": { description: Durum döndü }
        "401": { description: Yetkisiz }
  /api/invoices/{orderId}/pdf:
    get:
      summary: Fatura PDF indir (auth)
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: orderId
          required: true
          schema:
            type: string
      responses:
        "200": { description: PDF stream }
        "401": { description: Yetkisiz }
  /api/invoices/{orderId}/xml:
    get:
      summary: Fatura UBL/XML indir (auth)
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: orderId
          required: true
          schema:
            type: string
      responses:
        "200": { description: XML stream }
        "401": { description: Yetkisiz }
  /api/invoices:
    get:
      summary: Admin fatura listesi
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: channel
          schema: { type: string, enum: [einvoice, earchive] }
        - in: query
          name: status
          schema: { type: string, enum: [pending, sent, processing, approved, rejected, error] }
        - in: query
          name: from
          schema: { type: string, format: date-time }
        - in: query
          name: to
          schema: { type: string, format: date-time }
        - in: query
          name: page
          schema: { type: integer, minimum: 1, default: 1 }
        - in: query
          name: limit
          schema: { type: integer, minimum: 1, maximum: 100, default: 20 }
      responses:
        "200": { description: Liste }

  /api/invoices/{orderId}/links:
    post:
      summary: PDF/XML için imzalı link üretir (5 dk geçerli)
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: orderId
          required: true
          schema:
            type: string
      responses:
        "200": { description: Linkler üretildi }
        "401": { description: Yetkisiz }

  /public/invoices/{orderId}/pdf:
    get:
      summary: İmzalı token ile PDF indir (public)
      parameters:
        - in: path
          name: orderId
          required: true
          schema:
            type: string
        - in: query
          name: token
          schema:
            type: string
          required: true
      responses:
        "200": { description: PDF stream }
        "401": { description: Geçersiz token }

  /public/invoices/{orderId}/xml:
    get:
      summary: İmzalı token ile XML indir (public)
      parameters:
        - in: path
          name: orderId
          required: true
          schema:
            type: string
        - in: query
          name: token
          schema:
            type: string
          required: true
      responses:
        "200": { description: XML stream }
        "401": { description: Geçersiz token }

security:
  - bearerAuth: []
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT 