const MIN_PRODUCT_NAME_LENGTH = 3;
const MAX_PRODUCT_NAME_LENGTH = 50;
const MIN_PRODUCT_DESCRIPTION_LENGTH = 10;
const MAX_PRODUCT_DESCRIPTION_LENGTH = 3500;
const EMAIL_REGEX = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;

module.exports = {
    MIN_PRODUCT_NAME_LENGTH,
    MAX_PRODUCT_NAME_LENGTH,
    MIN_PRODUCT_DESCRIPTION_LENGTH,
    MAX_PRODUCT_DESCRIPTION_LENGTH,
    EMAIL_REGEX,
    };